import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { fetchList } from "../mock/api";
import { IItem } from "../types/item";

export async function getServerSideProps(context) {
  const list = await fetchList();

  return {
    props: {
      list,
    }, // will be passed to the page component as props
  };
}

interface IHomeProps {
  list: IItem[];
}

export default function Home({ list }: IHomeProps) {
  console.log("Home", { list });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <div>to csr detail</div>
          <ul className="flex w-full">
            {Array.isArray(list) &&
              list.map((item, i) => {
                return (
                  <Link key={i} href={`/csr/detail/${item.name}`} passHref>
                    <a target="_blank" className="flex justify-center">
                      <li className="w-1/3">
                        <Image src={item.img} alt={item.nameCn} width={300} height={300} objectFit="contain" />
                        <div>名字：{item.nameCn}</div>
                      </li>
                    </a>
                  </Link>
                );
              })}
          </ul>
        </div>
      </div>
    </div>
  );
}
