import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { fetchList } from "../mock/api";
import { IItem } from "../types/item";

export async function getStaticProps(context) {
  const list = await fetchList();

  return {
    props: {
      list,
    }, // will be passed to the page component as props
    revalidate: 10,
  };
}

interface IHomeProps {
  list: IItem[];
}

export default function Home({ list }: IHomeProps) {
  console.log("Home", { list });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <ul className="">
            {Array.isArray(list) &&
              list.map((item, i) => {
                return (
                  <li className="flex items-center" key={i}>
                    <div className="mr-[16px]">
                      <Image src={item.img} alt={item.nameCn} width={200} height={200} objectFit="contain" />
                    </div>
                    <div>
                      <div className="mb-[16px] text-xl">{item.nameCn}</div>
                      <Link href={`/csr/detail/${item.name}`} passHref>
                        <a target="_blank">
                          <div>to CSR detail</div>
                        </a>
                      </Link>
                      <Link href={`/ssr/detail/${item.name}`} passHref>
                        <a target="_blank">
                          <div>to SSR detail</div>
                        </a>
                      </Link>
                      <Link href={`/ssg/detail/${item.name}`} passHref>
                        <a target="_blank">
                          <div>to SSG detail</div>
                        </a>
                      </Link>
                    </div>
                  </li>
                );
              })}
          </ul>
        </div>
      </div>
    </div>
  );
}
